[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pytest.ini_options]
minversion = "6.0"
console_output_style = "count"
addopts = "--import-mode=importlib --pythonwarnings=ignore"
testpaths = "tests"
