logging:    # python logging
  # style: "%"    # { by default
  level: ${LOG_LEVEL:-INFO}
  format:
    date: '%Y-%m-%d %H:%M:%S'
    message: >- # newlines (not \n) interpreted as space; use \b to remove them
    #   %(asctime)s.%(msecs)03d %(levelname)-7s
    #   [%(filename)s:%(lineno)d] %(message)s
